site_name: pytest中文文档
site_url: https://pytest-zh.readthedocs.io/
repo_url: https://github.com/tim2anna/pytest-zh/
site_author: Tim2Anna
nav:
    - Home: index.md
    - About: about.md
theme: gitbook
plugins:
    - search:
        min_search_length: 2
